services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"     # RTSP
      - "8555:8555"     # RTSPS
      - "9997:9997"     # API
      - "9998:9998"     # Metrics
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
    restart: unless-stopped
    environment:
      - MTX_PROTOCOLS=tcp
    network_mode: bridge

  backendcam:
    container_name: backendcam
    build:
      context: .
      dockerfile: Dockerfile
    image: backendcam:latest
    depends_on:
      - mediamtx
    ports:
      - "8080:8080"
    environment:
      RTSP_HOST: 127.0.0.1
    volumes:
      - ./hls:/hls
    restart: unless-stopped
    network_mode: host