services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"     # RTSP
      - "8555:8555"     # RTSPS
      - "9997:9997"     # API
      - "9998:9998"     # Metrics
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/timezone:ro
    restart: unless-stopped
    environment:
      - MTX_PROTOCOLS=tcp
      - TZ=Asia/Bangkok
    network_mode: bridge

  backendcam:
    container_name: backendcam
    build:
      context: .
      dockerfile: Dockerfile
    image: backendcam:latest
    depends_on:
      - mediamtx
    ports:
      - "8080:8080"
    environment:
      RTSP_HOST: "127.0.0.1"
      TZ: "Asia/Bangkok"
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/serviceAccount.json"
    volumes:
      - ./hls:/hls
      - ./secrets/serviceAccount.json:/secrets/serviceAccount.json:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/timezone:ro
    restart: unless-stopped
    network_mode: host