services:
  
  backendcam:
    container_name: backendcam
    build:
      context: .
      dockerfile: Dockerfile
    image: backendcam:latest
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Bangkok"
      GOOGLE_APPLICATION_CREDENTIALS: "/secrets/serviceAccount.json"
    volumes:
      - ./hls:/hls
      - ./secrets/serviceAccount.json:/secrets/serviceAccount.json:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/localtime:ro
      - /usr/share/zoneinfo/Asia/Bangkok:/etc/timezone:ro
    restart: unless-stopped
    network_mode: host

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"   # controller listener
    environment:
      # KRaft settings (broker + controller in one)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # controller quorum config (just one node)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: "yes"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka